name: Deploy resources and config
on:
  push:
    branches:
      - main
      - no-secret

env:
  PROJECT: 'cpg-common'
  REFERENCES_PREFIX: 'gs://cpg-common-main/references'
  CONFIG_DESTINATION: 'gs://cpg-config/templates/references/references.toml'

jobs:
  make_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2

      - name: "Checkout revision before change"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }}
          path: 'before'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: "gcloud setup"
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT }}
          service_account_key: ${{ secrets.GCP_SERVER_DEPLOY_KEY }}
          export_default_credentials: true

      - name: "Set matrix"
        id: set_matrix
        run: |
          pip install cloudpathlib[all]
          cp references.py .github/workflows/references.py
          cp before/references.py .github/workflows/references_before.py;
          export REFERENCES_PREFIX=${{ env.REFERENCES_PREFIX }}
          echo "matrix=$(python .github/workflows/prep_matrix.py)" >> $GITHUB_OUTPUT
