name: Deploy references.toml
on:
  push:
    branches:
      - main
    paths:
      - 'references.toml'

  deploy_config:
    runs-on: ubuntu-latest
    needs:
      - deploy_images
    env:
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      CONFIG_DESTINATION: gs://cpg-config/templates
      PROJECT: 'cpg-common'
      REFERENCES_PREFIX: gs://cpg-reference
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: analysis-runner
          service_account_key: ${{ secrets.GCP_SERVER_DEPLOY_KEY }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - run: pip install click toml cpg_utils

      - run: |
          python .github/workflows/deploy.py \
          --no-dry-run /
          --project ${PROJECT} /
          --prefix ${REFERENCES_PREFIX} /
          --toml-path references.toml > references-ready.toml
  
      - name: "deploy config"
        run: |
          gcloud storage cp references-ready.toml \
          ${CONFIG_DESTINATION}/references/references.toml
